/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        syne: ['Syne', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        // Stitch typography tokens
        'display-lg': ['Syne', 'sans-serif'],
        'headline-lg': ['Syne', 'sans-serif'],
        'headline-lg-mobile': ['Syne', 'sans-serif'],
        'headline-md': ['Syne', 'sans-serif'],
        'body-lg': ['Outfit', 'sans-serif'],
        'body-md': ['Outfit', 'sans-serif'],
        'label-md': ['Outfit', 'sans-serif'],
        'label-sm': ['Outfit', 'sans-serif'],
      },
      colors: {
        brand: {
          // Surfaces
          dark: '#09090b',
          surface: '#131315',
          'surface-dim': '#131315',
          'surface-bright': '#39393b',
          'surface-lowest': '#0e0e10',
          'surface-container-low': '#1c1b1d',
          'surface-container': '#201f22',
          'surface-high': '#2a2a2c',
          'surface-highest': '#353437',
          'surface-base': '#18181b',
          'surface-variant': '#353437',
          // On-surface
          'on-surface': '#e5e1e4',
          'on-surface-variant': '#d1c6ab',
          'inverse-surface': '#e5e1e4',
          'inverse-on-surface': '#313032',
          // Primary (Neon Yellow)
          primary: '#ffecb9',
          'on-primary': '#3c2f00',
          yellow: '#facc15',
          'yellow-container': '#facc15',
          'on-yellow-container': '#6c5700',
          'yellow-light': '#ffecb9',
          'yellow-dim': '#eec200',
          'inverse-primary': '#735c00',
          'surface-tint': '#eec200',
          // Secondary (Emerald)
          emerald: '#4edea3',
          'on-emerald': '#003824',
          'emerald-container': '#00a572',
          'on-emerald-container': '#00311f',
          // Tertiary (Cyan)
          cyan: '#c7f5ff',
          'on-cyan': '#00363e',
          'cyan-container': '#33e4ff',
          'on-cyan-container': '#006270',
          // Error
          error: '#ffb4ab',
          'on-error': '#690005',
          'error-container': '#93000a',
          'on-error-container': '#ffdad6',
          // Outline
          outline: '#9a9078',
          'outline-variant': '#4d4632',
          // Misc
          orange: '#f97316',
        },
        // Stitch direct color tokens (used in Stitch HTML classes)
        'surface-container-lowest': '#0e0e10',
        'surface-container-low': '#1c1b1d',
        'surface-container': '#201f22',
        'surface-container-high': '#2a2a2c',
        'surface-container-highest': '#353437',
        'surface': '#131315',
        'surface-base': '#18181b',
        'surface-bright': '#39393b',
        'surface-dim': '#131315',
        'surface-variant': '#353437',
        'on-surface': '#e5e1e4',
        'on-surface-variant': '#d1c6ab',
        'on-background': '#e5e1e4',
        'background': '#131315',
        'primary': '#ffecb9',
        'on-primary': '#3c2f00',
        'primary-container': '#facc15',
        'on-primary-container': '#6c5700',
        'primary-fixed': '#ffe083',
        'primary-fixed-dim': '#eec200',
        'inverse-primary': '#735c00',
        'surface-tint': '#eec200',
        'secondary': '#4edea3',
        'on-secondary': '#003824',
        'secondary-container': '#00a572',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'tertiary': '#c7f5ff',
        'on-tertiary': '#00363e',
        'tertiary-container': '#33e4ff',
        'on-tertiary-container': '#006270',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'outline': '#9a9078',
        'outline-variant': '#4d4632',
        'inverse-surface': '#e5e1e4',
        'inverse-on-surface': '#313032',
        'border-low-light': 'rgba(255, 255, 255, 0.05)',
        'neon-yellow-glow': 'rgba(250, 204, 21, 0.4)',
        'background-accent': '#1e1b4b',
        'neon-yellow': '#facc15',
      },
      backgroundImage: {
        'glass-gradient': 'linear-gradient(135deg, rgba(255, 255, 255, 0.05) 0%, rgba(255, 255, 255, 0) 100%)',
      },
      backdropBlur: {
        xs: '2px',
        glass: '24px',
        'glass-modal': '40px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container': '1280px',
      },
      boxShadow: {
        'glow-yellow': '0 0 20px rgba(250, 204, 21, 0.3)',
        'glow-yellow-lg': '0 0 40px rgba(250, 204, 21, 0.4)',
        'glow-emerald': '0 0 20px rgba(78, 222, 163, 0.3)',
        'glow-cyan': '0 0 20px rgba(199, 245, 255, 0.3)',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
